// Servis API untuk mengambil data dari REST Countries API
const API_URL = 'https://restcountries.com/v3.1';

// Mock data untuk negara-negara (sementara API bermasalah)
const mockCountries = [
  {
    name: { common: "Indonesia", official: "Republic of Indonesia" },
    flags: { svg: "https://flagcdn.com/id.svg" },
    capital: ["Jakarta"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 273523615,
    languages: { ind: "Indonesian" },
    currencies: { IDR: { name: "Indonesian rupiah", symbol: "Rp" } },
    timezones: ["UTC+07:00", "UTC+08:00", "UTC+09:00"],
    cca2: "ID",
    cca3: "IDN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["2"] },
    borders: ["TLS", "MYS", "PNG"]
  },
  {
    name: { common: "United States", official: "United States of America" },
    flags: { svg: "https://flagcdn.com/us.svg" },
    capital: ["Washington, D.C."],
    region: "Americas",
    subregion: "North America",
    population: 329484123,
    languages: { eng: "English" },
    currencies: { USD: { name: "United States dollar", symbol: "$" } },
    timezones: ["UTC-12:00", "UTC-11:00", "UTC-10:00", "UTC-09:00", "UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC+10:00", "UTC+12:00"],
    cca2: "US",
    cca3: "USA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+1", suffixes: [""] },
    borders: ["CAN", "MEX"]
  },
  {
    name: { common: "Japan", official: "Japan" },
    flags: { svg: "https://flagcdn.com/jp.svg" },
    capital: ["Tokyo"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 125836021,
    languages: { jpn: "Japanese" },
    currencies: { JPY: { name: "Japanese yen", symbol: "¥" } },
    timezones: ["UTC+09:00"],
    cca2: "JP",
    cca3: "JPN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["1"] },
    borders: []
  },
  {
    name: { common: "Germany", official: "Federal Republic of Germany" },
    flags: { svg: "https://flagcdn.com/de.svg" },
    capital: ["Berlin"],
    region: "Europe",
    subregion: "Central Europe",
    population: 83240525,
    languages: { deu: "German" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "DE",
    cca3: "DEU",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["9"] },
    borders: ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"]
  },
  {
    name: { common: "Brazil", official: "Federative Republic of Brazil" },
    flags: { svg: "https://flagcdn.com/br.svg" },
    capital: ["Brasília"],
    region: "Americas",
    subregion: "South America",
    population: 212559409,
    languages: { por: "Portuguese" },
    currencies: { BRL: { name: "Brazilian real", symbol: "R$" } },
    timezones: ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
    cca2: "BR",
    cca3: "BRA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+5", suffixes: ["5"] },
    borders: ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"]
  },
  {
    name: { common: "Egypt", official: "Arab Republic of Egypt" },
    flags: { svg: "https://flagcdn.com/eg.svg" },
    capital: ["Cairo"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 102334403,
    languages: { ara: "Arabic" },
    currencies: { EGP: { name: "Egyptian pound", symbol: "£" } },
    timezones: ["UTC+02:00"],
    cca2: "EG",
    cca3: "EGY",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["0"] },
    borders: ["ISR", "LBY", "SDN"]
  },
  {
    name: { common: "Australia", official: "Commonwealth of Australia" },
    flags: { svg: "https://flagcdn.com/au.svg" },
    capital: ["Canberra"],
    region: "Oceania",
    subregion: "Australia and New Zealand",
    population: 25687041,
    languages: { eng: "English" },
    currencies: { AUD: { name: "Australian dollar", symbol: "$" } },
    timezones: ["UTC+05:00", "UTC+06:30", "UTC+07:00", "UTC+08:00", "UTC+09:30", "UTC+10:00", "UTC+11:00"],
    cca2: "AU",
    cca3: "AUS",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["1"] },
    borders: []
  },
  {
    name: { common: "Canada", official: "Canada" },
    flags: { svg: "https://flagcdn.com/ca.svg" },
    capital: ["Ottawa"],
    region: "Americas",
    subregion: "North America",
    population: 38005238,
    languages: { eng: "English", fra: "French" },
    currencies: { CAD: { name: "Canadian dollar", symbol: "$" } },
    timezones: ["UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC-03:30"],
    cca2: "CA",
    cca3: "CAN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+1", suffixes: [""] },
    borders: ["USA"]
  },
  {
    name: { common: "France", official: "French Republic" },
    flags: { svg: "https://flagcdn.com/fr.svg" },
    capital: ["Paris"],
    region: "Europe",
    subregion: "Western Europe",
    population: 67391582,
    languages: { fra: "French" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC-10:00", "UTC-09:30", "UTC-09:00", "UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC+01:00", "UTC+02:00", "UTC+03:00", "UTC+04:00", "UTC+05:00", "UTC+10:00", "UTC+11:00", "UTC+12:00"],
    cca2: "FR",
    cca3: "FRA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["3"] },
    borders: ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"]
  },
  {
    name: { common: "India", official: "Republic of India" },
    flags: { svg: "https://flagcdn.com/in.svg" },
    capital: ["New Delhi"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 1380004385,
    languages: { eng: "English", hin: "Hindi" },
    currencies: { INR: { name: "Indian rupee", symbol: "₹" } },
    timezones: ["UTC+05:30"],
    cca2: "IN",
    cca3: "IND",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["1"] },
    borders: ["BGD", "BTN", "MMR", "CHN", "NPL", "PAK"]
  },
  {
    name: { common: "China", official: "People's Republic of China" },
    flags: { svg: "https://flagcdn.com/cn.svg" },
    capital: ["Beijing"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 1402361450,
    languages: { zho: "Chinese" },
    currencies: { CNY: { name: "Chinese yuan", symbol: "¥" } },
    timezones: ["UTC+08:00"],
    cca2: "CN",
    cca3: "CHN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["6"] },
    borders: ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "PAK", "RUS", "TJK", "VNM"]
  },
  {
    name: { common: "Russia", official: "Russian Federation" },
    flags: { svg: "https://flagcdn.com/ru.svg" },
    capital: ["Moscow"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 146599183,
    languages: { rus: "Russian" },
    currencies: { RUB: { name: "Russian ruble", symbol: "₽" } },
    timezones: ["UTC+03:00", "UTC+04:00", "UTC+06:00", "UTC+07:00", "UTC+08:00", "UTC+09:00", "UTC+10:00", "UTC+11:00", "UTC+12:00"],
    cca2: "RU",
    cca3: "RUS",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+7", suffixes: [""] },
    borders: ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"]
  },
  {
    name: { common: "Mexico", official: "United Mexican States" },
    flags: { svg: "https://flagcdn.com/mx.svg" },
    capital: ["Mexico City"],
    region: "Americas",
    subregion: "North America",
    population: 128932753,
    languages: { spa: "Spanish" },
    currencies: { MXN: { name: "Mexican peso", symbol: "$" } },
    timezones: ["UTC-08:00", "UTC-07:00", "UTC-06:00"],
    cca2: "MX",
    cca3: "MEX",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+5", suffixes: ["2"] },
    borders: ["BLZ", "GTM", "USA"]
  },
  {
    name: { common: "Thailand", official: "Kingdom of Thailand" },
    flags: { svg: "https://flagcdn.com/th.svg" },
    capital: ["Bangkok"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 69799978,
    languages: { tha: "Thai" },
    currencies: { THB: { name: "Thai baht", symbol: "฿" } },
    timezones: ["UTC+07:00"],
    cca2: "TH",
    cca3: "THA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["6"] },
    borders: ["MMR", "KHM", "LAO", "MYS"]
  },
  {
    name: { common: "Italy", official: "Italian Republic" },
    flags: { svg: "https://flagcdn.com/it.svg" },
    capital: ["Rome"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 59554023,
    languages: { ita: "Italian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "IT",
    cca3: "ITA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["9"] },
    borders: ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"]
  },
  {
    name: { common: "South Korea", official: "Republic of Korea" },
    flags: { svg: "https://flagcdn.com/kr.svg" },
    capital: ["Seoul"],
    region: "Asia",
    subregion: "Eastern Asia",
    population: 51780579,
    languages: { kor: "Korean" },
    currencies: { KRW: { name: "South Korean won", symbol: "₩" } },
    timezones: ["UTC+09:00"],
    cca2: "KR",
    cca3: "KOR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["2"] },
    borders: ["PRK"]
  },
  {
    name: { common: "Turkey", official: "Republic of Turkey" },
    flags: { svg: "https://flagcdn.com/tr.svg" },
    capital: ["Ankara"],
    region: "Asia",
    subregion: "Western Asia",
    population: 84339067,
    languages: { tur: "Turkish" },
    currencies: { TRY: { name: "Turkish lira", symbol: "₺" } },
    timezones: ["UTC+03:00"],
    cca2: "TR",
    cca3: "TUR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["0"] },
    borders: ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"]
  },
  {
    name: { common: "United Kingdom", official: "United Kingdom of Great Britain and Northern Ireland" },
    flags: { svg: "https://flagcdn.com/gb.svg" },
    capital: ["London"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 67215293,
    languages: { eng: "English" },
    currencies: { GBP: { name: "British pound", symbol: "£" } },
    timezones: ["UTC-08:00", "UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC+00:00", "UTC+01:00"],
    cca2: "GB",
    cca3: "GBR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["4"] },
    borders: ["IRL"]
  },
  {
    name: { common: "Spain", official: "Kingdom of Spain" },
    flags: { svg: "https://flagcdn.com/es.svg" },
    capital: ["Madrid"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 47351567,
    languages: { spa: "Spanish" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC-01:00", "UTC+00:00", "UTC+01:00"],
    cca2: "ES",
    cca3: "ESP",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["4"] },
    borders: ["AND", "FRA", "GIB", "PRT", "MAR"]
  },
  {
    name: { common: "Saudi Arabia", official: "Kingdom of Saudi Arabia" },
    flags: { svg: "https://flagcdn.com/sa.svg" },
    capital: ["Riyadh"],
    region: "Asia",
    subregion: "Western Asia",
    population: 34813867,
    languages: { ara: "Arabic" },
    currencies: { SAR: { name: "Saudi riyal", symbol: "﷼" } },
    timezones: ["UTC+03:00"],
    cca2: "SA",
    cca3: "SAU",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["6"] },
    borders: ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"]
  },
  {
    name: { common: "Switzerland", official: "Swiss Confederation" },
    flags: { svg: "https://flagcdn.com/ch.svg" },
    capital: ["Bern"],
    region: "Europe",
    subregion: "Central Europe",
    population: 8636896,
    languages: { fra: "French", deu: "German", ita: "Italian", roh: "Romansh" },
    currencies: { CHF: { name: "Swiss franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "CH",
    cca3: "CHE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["1"] },
    borders: ["AUT", "FRA", "ITA", "LIE", "DEU"]
  },
  {
    name: { common: "Netherlands", official: "Kingdom of the Netherlands" },
    flags: { svg: "https://flagcdn.com/nl.svg" },
    capital: ["Amsterdam"],
    region: "Europe",
    subregion: "Western Europe",
    population: 17441790,
    languages: { nld: "Dutch" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC-04:00", "UTC+01:00"],
    cca2: "NL",
    cca3: "NLD",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["1"] },
    borders: ["BEL", "DEU"]
  },
  {
    name: { common: "Sweden", official: "Kingdom of Sweden" },
    flags: { svg: "https://flagcdn.com/se.svg" },
    capital: ["Stockholm"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 10353442,
    languages: { swe: "Swedish" },
    currencies: { SEK: { name: "Swedish krona", symbol: "kr" } },
    timezones: ["UTC+01:00"],
    cca2: "SE",
    cca3: "SWE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["6"] },
    borders: ["FIN", "NOR"]
  },
  {
    name: { common: "Norway", official: "Kingdom of Norway" },
    flags: { svg: "https://flagcdn.com/no.svg" },
    capital: ["Oslo"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 5379475,
    languages: { nor: "Norwegian" },
    currencies: { NOK: { name: "Norwegian krone", symbol: "kr" } },
    timezones: ["UTC+01:00"],
    cca2: "NO",
    cca3: "NOR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["7"] },
    borders: ["FIN", "SWE", "RUS"]
  },
  {
    name: { common: "Denmark", official: "Kingdom of Denmark" },
    flags: { svg: "https://flagcdn.com/dk.svg" },
    capital: ["Copenhagen"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 5831404,
    languages: { dan: "Danish" },
    currencies: { DKK: { name: "Danish krone", symbol: "kr" } },
    timezones: ["UTC+01:00"],
    cca2: "DK",
    cca3: "DNK",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["5"] },
    borders: ["DEU"]
  },
  {
    name: { common: "Finland", official: "Republic of Finland" },
    flags: { svg: "https://flagcdn.com/fi.svg" },
    capital: ["Helsinki"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 5530719,
    languages: { fin: "Finnish", swe: "Swedish" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+02:00"],
    cca2: "FI",
    cca3: "FIN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["5"] },
    borders: ["NOR", "SWE", "RUS"]
  },
  {
    name: { common: "Ireland", official: "Republic of Ireland" },
    flags: { svg: "https://flagcdn.com/ie.svg" },
    capital: ["Dublin"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 4994724,
    languages: { eng: "English", gle: "Irish" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+00:00"],
    cca2: "IE",
    cca3: "IRL",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["53"] },
    borders: ["GBR"]
  },
  {
    name: { common: "Belgium", official: "Kingdom of Belgium" },
    flags: { svg: "https://flagcdn.com/be.svg" },
    capital: ["Brussels"],
    region: "Europe",
    subregion: "Western Europe",
    population: 11555997,
    languages: { fra: "French", deu: "German", nld: "Dutch" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "BE",
    cca3: "BEL",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["2"] },
    borders: ["FRA", "DEU", "LUX", "NLD"]
  },
  {
    name: { common: "Austria", official: "Republic of Austria" },
    flags: { svg: "https://flagcdn.com/at.svg" },
    capital: ["Vienna"],
    region: "Europe",
    subregion: "Central Europe",
    population: 8917205,
    languages: { deu: "German" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "AT",
    cca3: "AUT",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["3"] },
    borders: ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"]
  },
  {
    name: { common: "Greece", official: "Hellenic Republic" },
    flags: { svg: "https://flagcdn.com/gr.svg" },
    capital: ["Athens"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 10715549,
    languages: { ell: "Greek" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+02:00"],
    cca2: "GR",
    cca3: "GRC",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["0"] },
    borders: ["ALB", "BGR", "TUR", "MKD"]
  },
  {
    name: { common: "Portugal", official: "Portuguese Republic" },
    flags: { svg: "https://flagcdn.com/pt.svg" },
    capital: ["Lisbon"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 10305564,
    languages: { por: "Portuguese" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC-01:00", "UTC+00:00"],
    cca2: "PT",
    cca3: "PRT",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["51"] },
    borders: ["ESP"]
  },
  {
    name: { common: "Poland", official: "Republic of Poland" },
    flags: { svg: "https://flagcdn.com/pl.svg" },
    capital: ["Warsaw"],
    region: "Europe",
    subregion: "Central Europe",
    population: 37950802,
    languages: { pol: "Polish" },
    currencies: { PLN: { name: "Polish złoty", symbol: "zł" } },
    timezones: ["UTC+01:00"],
    cca2: "PL",
    cca3: "POL",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["8"] },
    borders: ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"]
  },
  {
    name: { common: "Romania", official: "Romania" },
    flags: { svg: "https://flagcdn.com/ro.svg" },
    capital: ["Bucharest"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 19286123,
    languages: { ron: "Romanian" },
    currencies: { RON: { name: "Romanian leu", symbol: "lei" } },
    timezones: ["UTC+02:00"],
    cca2: "RO",
    cca3: "ROU",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["0"] },
    borders: ["BGR", "HUN", "MDA", "SRB", "UKR"]
  },
  {
    name: { common: "Czech Republic", official: "Czech Republic" },
    flags: { svg: "https://flagcdn.com/cz.svg" },
    capital: ["Prague"],
    region: "Europe",
    subregion: "Central Europe",
    population: 10476011,
    languages: { ces: "Czech" },
    currencies: { CZK: { name: "Czech koruna", symbol: "Kč" } },
    timezones: ["UTC+01:00"],
    cca2: "CZ",
    cca3: "CZE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["20"] },
    borders: ["AUT", "DEU", "POL", "SVK"]
  },
  {
    name: { common: "Hungary", official: "Hungary" },
    flags: { svg: "https://flagcdn.com/hu.svg" },
    capital: ["Budapest"],
    region: "Europe",
    subregion: "Central Europe",
    population: 9749763,
    languages: { hun: "Hungarian" },
    currencies: { HUF: { name: "Hungarian forint", symbol: "Ft" } },
    timezones: ["UTC+01:00"],
    cca2: "HU",
    cca3: "HUN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["6"] },
    borders: ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"]
  },
  {
    name: { common: "Serbia", official: "Republic of Serbia" },
    flags: { svg: "https://flagcdn.com/rs.svg" },
    capital: ["Belgrade"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 6908224,
    languages: { srp: "Serbian" },
    currencies: { RSD: { name: "Serbian dinar", symbol: "дин." } },
    timezones: ["UTC+01:00"],
    cca2: "RS",
    cca3: "SRB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["81"] },
    borders: ["BIH", "BGR", "HRV", "HUN", "UNK", "MKD", "MNE", "ROU"]
  },
  {
    name: { common: "Croatia", official: "Republic of Croatia" },
    flags: { svg: "https://flagcdn.com/hr.svg" },
    capital: ["Zagreb"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 4047200,
    languages: { hrv: "Croatian" },
    currencies: { HRK: { name: "Croatian kuna", symbol: "kn" } },
    timezones: ["UTC+01:00"],
    cca2: "HR",
    cca3: "HRV",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["85"] },
    borders: ["BIH", "HUN", "MNE", "SRB", "SVN"]
  },
  {
    name: { common: "Bulgaria", official: "Republic of Bulgaria" },
    flags: { svg: "https://flagcdn.com/bg.svg" },
    capital: ["Sofia"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 6927288,
    languages: { bul: "Bulgarian" },
    currencies: { BGN: { name: "Bulgarian lev", symbol: "лв" } },
    timezones: ["UTC+02:00"],
    cca2: "BG",
    cca3: "BGR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["59"] },
    borders: ["GRC", "MKD", "ROU", "SRB", "TUR"]
  },
  {
    name: { common: "Slovakia", official: "Slovak Republic" },
    flags: { svg: "https://flagcdn.com/sk.svg" },
    capital: ["Bratislava"],
    region: "Europe",
    subregion: "Central Europe",
    population: 5458827,
    languages: { slk: "Slovak" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "SK",
    cca3: "SVK",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["21"] },
    borders: ["AUT", "CZE", "HUN", "POL", "UKR"]
  },
  {
    name: { common: "Slovenia", official: "Republic of Slovenia" },
    flags: { svg: "https://flagcdn.com/si.svg" },
    capital: ["Ljubljana"],
    region: "Europe",
    subregion: "Central Europe",
    population: 2078938,
    languages: { slv: "Slovenian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "SI",
    cca3: "SVN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["86"] },
    borders: ["AUT", "HRV", "ITA", "HUN"]
  },
  {
    name: { common: "Estonia", official: "Republic of Estonia" },
    flags: { svg: "https://flagcdn.com/ee.svg" },
    capital: ["Tallinn"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 1331057,
    languages: { est: "Estonian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+02:00"],
    cca2: "EE",
    cca3: "EST",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["72"] },
    borders: ["LVA", "RUS"]
  },
  {
    name: { common: "Latvia", official: "Republic of Latvia" },
    flags: { svg: "https://flagcdn.com/lv.svg" },
    capital: ["Riga"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 1901548,
    languages: { lav: "Latvian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+02:00"],
    cca2: "LV",
    cca3: "LVA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["71"] },
    borders: ["BLR", "EST", "LTU", "RUS"]
  },
  {
    name: { common: "Lithuania", official: "Republic of Lithuania" },
    flags: { svg: "https://flagcdn.com/lt.svg" },
    capital: ["Vilnius"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 2794700,
    languages: { lit: "Lithuanian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+02:00"],
    cca2: "LT",
    cca3: "LTU",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["70"] },
    borders: ["BLR", "LVA", "POL", "RUS"]
  },
  {
    name: { common: "Luxembourg", official: "Grand Duchy of Luxembourg" },
    flags: { svg: "https://flagcdn.com/lu.svg" },
    capital: ["Luxembourg"],
    region: "Europe",
    subregion: "Western Europe",
    population: 632275,
    languages: { fra: "French", deu: "German", ltz: "Luxembourgish" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "LU",
    cca3: "LUX",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["52"] },
    borders: ["BEL", "FRA", "DEU"]
  },
  {
    name: { common: "Malta", official: "Republic of Malta" },
    flags: { svg: "https://flagcdn.com/mt.svg" },
    capital: ["Valletta"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 525285,
    languages: { mlt: "Maltese", eng: "English" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "MT",
    cca3: "MLT",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["56"] },
    borders: []
  },
  {
    name: { common: "Cyprus", official: "Republic of Cyprus" },
    flags: { svg: "https://flagcdn.com/cy.svg" },
    capital: ["Nicosia"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 1207359,
    languages: { ell: "Greek", tur: "Turkish" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+02:00"],
    cca2: "CY",
    cca3: "CYP",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["57"] },
    borders: []
  },
  {
    name: { common: "Iceland", official: "Iceland" },
    flags: { svg: "https://flagcdn.com/is.svg" },
    capital: ["Reykjavik"],
    region: "Europe",
    subregion: "Northern Europe",
    population: 366425,
    languages: { isl: "Icelandic" },
    currencies: { ISK: { name: "Icelandic króna", symbol: "kr" } },
    timezones: ["UTC+00:00"],
    cca2: "IS",
    cca3: "ISL",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["54"] },
    borders: []
  },
  {
    name: { common: "Monaco", official: "Principality of Monaco" },
    flags: { svg: "https://flagcdn.com/mc.svg" },
    capital: ["Monaco"],
    region: "Europe",
    subregion: "Western Europe",
    population: 39242,
    languages: { fra: "French" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "MC",
    cca3: "MCO",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["77"] },
    borders: ["FRA"]
  },
  {
    name: { common: "San Marino", official: "Most Serene Republic of San Marino" },
    flags: { svg: "https://flagcdn.com/sm.svg" },
    capital: ["City of San Marino"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 33938,
    languages: { ita: "Italian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "SM",
    cca3: "SMR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["78"] },
    borders: ["ITA"]
  },
  {
    name: { common: "Liechtenstein", official: "Principality of Liechtenstein" },
    flags: { svg: "https://flagcdn.com/li.svg" },
    capital: ["Vaduz"],
    region: "Europe",
    subregion: "Central Europe",
    population: 38137,
    languages: { deu: "German" },
    currencies: { CHF: { name: "Swiss franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "LI",
    cca3: "LIE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+4", suffixes: ["23"] },
    borders: ["AUT", "CHE"]
  },
  {
    name: { common: "Vatican City", official: "Vatican City State" },
    flags: { svg: "https://flagcdn.com/va.svg" },
    capital: ["Vatican City"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 451,
    languages: { ita: "Italian", lat: "Latin" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "VA",
    cca3: "VAT",
    independent: true,
    status: " sovereign",
    unMember: false,
    idd: { root: "+3", suffixes: ["96"] },
    borders: ["ITA"]
  },
  {
    name: { common: "Andorra", official: "Principality of Andorra" },
    flags: { svg: "https://flagcdn.com/ad.svg" },
    capital: ["Andorra la Vella"],
    region: "Europe",
    subregion: "Southern Europe",
    population: 77265,
    languages: { cat: "Catalan" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "AD",
    cca3: "AND",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["76"] },
    borders: ["FRA", "ESP"]
  },
  {
    name: { common: "Albania", official: "Republic of Albania" },
    flags: { svg: "https://flagcdn.com/al.svg" },
    capital: ["Tirana"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 2837743,
    languages: { sqi: "Albanian" },
    currencies: { ALL: { name: "Albanian lek", symbol: "L" } },
    timezones: ["UTC+01:00"],
    cca2: "AL",
    cca3: "ALB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["55"] },
    borders: ["GRC", "MKD", "MNE", "SRB"]
  },
  {
    name: { common: "North Macedonia", official: "Republic of North Macedonia" },
    flags: { svg: "https://flagcdn.com/mk.svg" },
    capital: ["Skopje"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 2083380,
    languages: { mkd: "Macedonian" },
    currencies: { MKD: { name: "denar", symbol: "den" } },
    timezones: ["UTC+01:00"],
    cca2: "MK",
    cca3: "MKD",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["89"] },
    borders: ["ALB", "BGR", "GRC", "UNK", "SRB"]
  },
  {
    name: { common: "Montenegro", official: "Montenegro" },
    flags: { svg: "https://flagcdn.com/me.svg" },
    capital: ["Podgorica"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 621718,
    languages: { cnr: "Montenegrin" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "ME",
    cca3: "MNE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["82"] },
    borders: ["ALB", "BIH", "HRV", "UNK", "SRB"]
  },
  {
    name: { common: "Bosnia and Herzegovina", official: "Bosnia and Herzegovina" },
    flags: { svg: "https://flagcdn.com/ba.svg" },
    capital: ["Sarajevo"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 3280815,
    languages: { bos: "Bosnian", hrv: "Croatian", srp: "Serbian" },
    currencies: { BAM: { name: "Bosnia and Herzegovina convertible mark", symbol: "KM" } },
    timezones: ["UTC+01:00"],
    cca2: "BA",
    cca3: "BIH",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["87"] },
    borders: ["HRV", "MNE", "SRB"]
  },
  {
    name: { common: "Kosovo", official: "Republic of Kosovo" },
    flags: { svg: "https://flagcdn.com/xk.svg" },
    capital: ["Pristina"],
    region: "Europe",
    subregion: "Southeast Europe",
    population: 1775378,
    languages: { sqi: "Albanian", srp: "Serbian" },
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    timezones: ["UTC+01:00"],
    cca2: "XK",
    cca3: "UNK",
    independent: true,
    status: " sovereign",
    unMember: false,
    idd: { root: "+3", suffixes: ["83"] },
    borders: ["ALB", "MKD", "MNE", "SRB", "BIH"]
  },
  {
    name: { common: "Ukraine", official: "Ukraine" },
    flags: { svg: "https://flagcdn.com/ua.svg" },
    capital: ["Kyiv"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 44134693,
    languages: { ukr: "Ukrainian" },
    currencies: { UAH: { name: "Ukrainian hryvnia", symbol: "₴" } },
    timezones: ["UTC+02:00"],
    cca2: "UA",
    cca3: "UKR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["80"] },
    borders: ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"]
  },
  {
    name: { common: "Belarus", official: "Republic of Belarus" },
    flags: { svg: "https://flagcdn.com/by.svg" },
    capital: ["Minsk"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 9398861,
    languages: { bel: "Belarusian", rus: "Russian" },
    currencies: { BYN: { name: "Belarusian ruble", symbol: "Br" } },
    timezones: ["UTC+03:00"],
    cca2: "BY",
    cca3: "BLR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["75"] },
    borders: ["LVA", "LTU", "POL", "RUS", "UKR"]
  },
  {
    name: { common: "Moldova", official: "Republic of Moldova" },
    flags: { svg: "https://flagcdn.com/md.svg" },
    capital: ["Chișinău"],
    region: "Europe",
    subregion: "Eastern Europe",
    population: 2617820,
    languages: { ron: "Moldavian" },
    currencies: { MDL: { name: "Moldovan leu", symbol: "L" } },
    timezones: ["UTC+02:00"],
    cca2: "MD",
    cca3: "MDA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["73"] },
    borders: ["ROU", "UKR"]
  },
  {
    name: { common: "Georgia", official: "Georgia" },
    flags: { svg: "https://flagcdn.com/ge.svg" },
    capital: ["Tbilisi"],
    region: "Asia",
    subregion: "Western Asia",
    population: 3714000,
    languages: { kat: "Georgian" },
    currencies: { GEL: { name: "lari", symbol: "₾" } },
    timezones: ["UTC+04:00"],
    cca2: "GE",
    cca3: "GEO",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["95"] },
    borders: ["ARM", "AZE", "RUS", "TUR"]
  },
  {
    name: { common: "Armenia", official: "Republic of Armenia" },
    flags: { svg: "https://flagcdn.com/am.svg" },
    capital: ["Yerevan"],
    region: "Asia",
    subregion: "Western Asia",
    population: 2963234,
    languages: { hye: "Armenian" },
    currencies: { AMD: { name: "Armenian dram", symbol: "֏" } },
    timezones: ["UTC+04:00"],
    cca2: "AM",
    cca3: "ARM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+3", suffixes: ["74"] },
    borders: ["AZE", "GEO", "IRN", "TUR"]
  },
  {
    name: { common: "Azerbaijan", official: "Republic of Azerbaijan" },
    flags: { svg: "https://flagcdn.com/az.svg" },
    capital: ["Baku"],
    region: "Asia",
    subregion: "Western Asia",
    population: 10110116,
    languages: { aze: "Azerbaijani" },
    currencies: { AZN: { name: "Azerbaijani manat", symbol: "₼" } },
    timezones: ["UTC+04:00"],
    cca2: "AZ",
    cca3: "AZE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["94"] },
    borders: ["ARM", "GEO", "IRN", "RUS", "TUR"]
  },
  {
    name: { common: "Kazakhstan", official: "Republic of Kazakhstan" },
    flags: { svg: "https://flagcdn.com/kz.svg" },
    capital: ["Nur-Sultan"],
    region: "Asia",
    subregion: "Central Asia",
    population: 18754440,
    languages: { kaz: "Kazakh", rus: "Russian" },
    currencies: { KZT: { name: "Kazakhstani tenge", symbol: "₸" } },
    timezones: ["UTC+05:00", "UTC+06:00"],
    cca2: "KZ",
    cca3: "KAZ",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+7", suffixes: ["6"] },
    borders: ["CHN", "KGZ", "RUS", "TKM", "UZB"]
  },
  {
    name: { common: "Kyrgyzstan", official: "Kyrgyz Republic" },
    flags: { svg: "https://flagcdn.com/kg.svg" },
    capital: ["Bishkek"],
    region: "Asia",
    subregion: "Central Asia",
    population: 6591600,
    languages: { kir: "Kyrgyz", rus: "Russian" },
    currencies: { KGS: { name: "Kyrgyzstani som", symbol: "с" } },
    timezones: ["UTC+06:00"],
    cca2: "KG",
    cca3: "KGZ",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["96"] },
    borders: ["CHN", "KAZ", "TJK", "UZB"]
  },
  {
    name: { common: "Tajikistan", official: "Republic of Tajikistan" },
    flags: { svg: "https://flagcdn.com/tj.svg" },
    capital: ["Dushanbe"],
    region: "Asia",
    subregion: "Central Asia",
    population: 9537642,
    languages: { tgk: "Tajik", rus: "Russian" },
    currencies: { TJS: { name: "Tajikistani somoni", symbol: "ЅМ" } },
    timezones: ["UTC+05:00"],
    cca2: "TJ",
    cca3: "TJK",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["92"] },
    borders: ["AFG", "CHN", "KGZ", "UZB"]
  },
  {
    name: { common: "Turkmenistan", official: "Turkmenistan" },
    flags: { svg: "https://flagcdn.com/tm.svg" },
    capital: ["Ashgabat"],
    region: "Asia",
    subregion: "Central Asia",
    population: 6031187,
    languages: { tuk: "Turkmen", rus: "Russian" },
    currencies: { TMT: { name: "Turkmenistan manat", symbol: "T" } },
    timezones: ["UTC+05:00"],
    cca2: "TM",
    cca3: "TKM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["93"] },
    borders: ["AFG", "IRN", "KAZ", "UZB"]
  },
  {
    name: { common: "Uzbekistan", official: "Republic of Uzbekistan" },
    flags: { svg: "https://flagcdn.com/uz.svg" },
    capital: ["Tashkent"],
    region: "Asia",
    subregion: "Central Asia",
    population: 34232050,
    languages: { uzb: "Uzbek" },
    currencies: { UZS: { name: "Uzbekistani so'm", symbol: "so'm" } },
    timezones: ["UTC+05:00"],
    cca2: "UZ",
    cca3: "UZB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["98"] },
    borders: ["AFG", "KAZ", "KGZ", "TJK", "TKM"]
  },
  {
    name: { common: "Afghanistan", official: "Islamic Republic of Afghanistan" },
    flags: { svg: "https://flagcdn.com/af.svg" },
    capital: ["Kabul"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 40218234,
    languages: { prs: "Dari", pus: "Pashto", tuk: "Turkmen" },
    currencies: { AFN: { name: "Afghan afghani", symbol: "؋" } },
    timezones: ["UTC+04:30"],
    cca2: "AF",
    cca3: "AFG",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["3"] },
    borders: ["IRN", "PAK", "TKM", "TJK", "UZB", "CHN"]
  },
  {
    name: { common: "Bangladesh", official: "People's Republic of Bangladesh" },
    flags: { svg: "https://flagcdn.com/bd.svg" },
    capital: ["Dhaka"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 164689383,
    languages: { ben: "Bengali" },
    currencies: { BDT: { name: "Bangladeshi taka", symbol: "৳" } },
    timezones: ["UTC+06:00"],
    cca2: "BD",
    cca3: "BGD",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["80"] },
    borders: ["MMR", "CHN", "IND"]
  },
  {
    name: { common: "Bhutan", official: "Kingdom of Bhutan" },
    flags: { svg: "https://flagcdn.com/bt.svg" },
    capital: ["Thimphu"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 771612,
    languages: { dzo: "Dzongkha" },
    currencies: { BTN: { name: "Bhutanese ngultrum", symbol: "Nu." }, INR: { name: "Indian rupee", symbol: "₹" } },
    timezones: ["UTC+06:00"],
    cca2: "BT",
    cca3: "BTN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["75"] },
    borders: ["CHN", "IND"]
  },
  {
    name: { common: "Maldives", official: "Republic of Maldives" },
    flags: { svg: "https://flagcdn.com/mv.svg" },
    capital: ["Malé"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 540542,
    languages: { div: "Maldivian" },
    currencies: { MVR: { name: "Maldivian rufiyaa", symbol: ".ރ" } },
    timezones: ["UTC+05:00"],
    cca2: "MV",
    cca3: "MDV",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["60"] },
    borders: []
  },
  {
    name: { common: "Nepal", official: "Federal Democratic Republic of Nepal" },
    flags: { svg: "https://flagcdn.com/np.svg" },
    capital: ["Kathmandu"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 29136808,
    languages: { nep: "Nepali" },
    currencies: { NPR: { name: "Nepalese rupee", symbol: "₨" } },
    timezones: ["UTC+05:45"],
    cca2: "NP",
    cca3: "NPL",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["77"] },
    borders: ["CHN", "IND"]
  },
  {
    name: { common: "Pakistan", official: "Islamic Republic of Pakistan" },
    flags: { svg: "https://flagcdn.com/pk.svg" },
    capital: ["Islamabad"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 220892331,
    languages: { eng: "English", urd: "Urdu" },
    currencies: { PKR: { name: "Pakistani rupee", symbol: "₨" } },
    timezones: ["UTC+05:00"],
    cca2: "PK",
    cca3: "PAK",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["2"] },
    borders: ["AFG", "CHN", "IND", "IRN"]
  },
  {
    name: { common: "Sri Lanka", official: "Democratic Socialist Republic of Sri Lanka" },
    flags: { svg: "https://flagcdn.com/lk.svg" },
    capital: ["Colombo"],
    region: "Asia",
    subregion: "Southern Asia",
    population: 21919000,
    languages: { sin: "Sinhala", tam: "Tamil" },
    currencies: { LKR: { name: "Sri Lankan rupee", symbol: "Rs  රු" } },
    timezones: ["UTC+05:30"],
    cca2: "LK",
    cca3: "LKA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["4"] },
    borders: []
  },
  {
    name: { common: "Brunei", official: "Nation of Brunei, Abode of Peace" },
    flags: { svg: "https://flagcdn.com/bn.svg" },
    capital: ["Bandar Seri Begawan"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 437483,
    languages: { msa: "Malay" },
    currencies: { BND: { name: "Brunei dollar", symbol: "$" }, SGD: { name: "Singapore dollar", symbol: "$" } },
    timezones: ["UTC+08:00"],
    cca2: "BN",
    cca3: "BRN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["73"] },
    borders: ["MYS"]
  },
  {
    name: { common: "Cambodia", official: "Kingdom of Cambodia" },
    flags: { svg: "https://flagcdn.com/kh.svg" },
    capital: ["Phnom Penh"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 16718971,
    languages: { khm: "Khmer" },
    currencies: { KHR: { name: "Cambodian riel", symbol: "៛" }, USD: { name: "United States dollar", symbol: "$" } },
    timezones: ["UTC+07:00"],
    cca2: "KH",
    cca3: "KHM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["55"] },
    borders: ["LAO", "THA", "VNM"]
  },
  {
    name: { common: "East Timor", official: "Democratic Republic of Timor-Leste" },
    flags: { svg: "https://flagcdn.com/tl.svg" },
    capital: ["Dili"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 1318360,
    languages: { por: "Portuguese", tet: "Tetum" },
    currencies: { USD: { name: "United States dollar", symbol: "$" } },
    timezones: ["UTC+09:00"],
    cca2: "TL",
    cca3: "TLS",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["70"] },
    borders: ["IDN"]
  },
  {
    name: { common: "Laos", official: "Lao People's Democratic Republic" },
    flags: { svg: "https://flagcdn.com/la.svg" },
    capital: ["Vientiane"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 7275556,
    languages: { lao: "Lao" },
    currencies: { LAK: { name: "Lao kip", symbol: "₭" } },
    timezones: ["UTC+07:00"],
    cca2: "LA",
    cca3: "LAO",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["56"] },
    borders: ["MMR", "KHM", "CHN", "THA", "VNM"]
  },
  {
    name: { common: "Myanmar", official: "Republic of the Union of Myanmar" },
    flags: { svg: "https://flagcdn.com/mm.svg" },
    capital: ["Naypyidaw"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 54409794,
    languages: { mya: "Burmese" },
    currencies: { MMK: { name: "Burmese kyat", symbol: "Ks" } },
    timezones: ["UTC+06:30"],
    cca2: "MM",
    cca3: "MMR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+9", suffixes: ["5"] },
    borders: ["BGD", "CHN", "IND", "LAO", "THA"]
  },
  {
    name: { common: "Philippines", official: "Republic of the Philippines" },
    flags: { svg: "https://flagcdn.com/ph.svg" },
    capital: ["Manila"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 109581078,
    languages: { eng: "English", fil: "Filipino" },
    currencies: { PHP: { name: "Philippine peso", symbol: "₱" } },
    timezones: ["UTC+08:00"],
    cca2: "PH",
    cca3: "PHL",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["3"] },
    borders: []
  },
  {
    name: { common: "Singapore", official: "Republic of Singapore" },
    flags: { svg: "https://flagcdn.com/sg.svg" },
    capital: ["Singapore"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 5685807,
    languages: { zho: "Chinese", eng: "English", msa: "Malay", tam: "Tamil" },
    currencies: { SGD: { name: "Singapore dollar", symbol: "$" } },
    timezones: ["UTC+08:00"],
    cca2: "SG",
    cca3: "SGP",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+6", suffixes: ["5"] },
    borders: []
  },
  {
    name: { common: "Vietnam", official: "Socialist Republic of Vietnam" },
    flags: { svg: "https://flagcdn.com/vn.svg" },
    capital: ["Hanoi"],
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 97338583,
    languages: { vie: "Vietnamese" },
    currencies: { VND: { name: "Vietnamese đồng", symbol: "₫" } },
    timezones: ["UTC+07:00"],
    cca2: "VN",
    cca3: "VNM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+8", suffixes: ["4"] },
    borders: ["KHM", "CHN", "LAO"]
  },
  {
    name: { common: "Angola", official: "Republic of Angola" },
    flags: { svg: "https://flagcdn.com/ao.svg" },
    capital: ["Luanda"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 32866268,
    languages: { por: "Portuguese" },
    currencies: { AOA: { name: "Angolan kwanza", symbol: "Kz" } },
    timezones: ["UTC+01:00"],
    cca2: "AO",
    cca3: "AGO",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["44"] },
    borders: ["COG", "COD", "ZMB", "NAM"]
  },
  {
    name: { common: "Benin", official: "Republic of Benin" },
    flags: { svg: "https://flagcdn.com/bj.svg" },
    capital: ["Porto-Novo"],
    region: "Africa",
    subregion: "Western Africa",
    population: 12123198,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "BJ",
    cca3: "BEN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["29"] },
    borders: ["BFA", "NER", "NGA", "TGO"]
  },
  {
    name: { common: "Botswana", official: "Republic of Botswana" },
    flags: { svg: "https://flagcdn.com/bw.svg" },
    capital: ["Gaborone"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 2351625,
    languages: { eng: "English", tsn: "Tswana" },
    currencies: { BWP: { name: "Botswana pula", symbol: "P" } },
    timezones: ["UTC+02:00"],
    cca2: "BW",
    cca3: "BWA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["67"] },
    borders: ["NAM", "ZAF", "ZMB", "ZWE"]
  },
  {
    name: { common: "Burkina Faso", official: "Burkina Faso" },
    flags: { svg: "https://flagcdn.com/bf.svg" },
    capital: ["Ouagadougou"],
    region: "Africa",
    subregion: "Western Africa",
    population: 20903273,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "BF",
    cca3: "BFA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["26"] },
    borders: ["BEN", "CIV", "GHA", "MLI", "NER", "TGO"]
  },
  {
    name: { common: "Burundi", official: "Republic of Burundi" },
    flags: { svg: "https://flagcdn.com/bi.svg" },
    capital: ["Gitega"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 11890781,
    languages: { fra: "French", run: "Kirundi" },
    currencies: { BIF: { name: "Burundian franc", symbol: "Fr" } },
    timezones: ["UTC+02:00"],
    cca2: "BI",
    cca3: "BDI",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["57"] },
    borders: ["COD", "RWA", "TZA"]
  },
  {
    name: { common: "Cameroon", official: "Republic of Cameroon" },
    flags: { svg: "https://flagcdn.com/cm.svg" },
    capital: ["Yaoundé"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 26545864,
    languages: { eng: "English", fra: "French" },
    currencies: { XAF: { name: "Central African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "CM",
    cca3: "CMR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["37"] },
    borders: ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"]
  },
  {
    name: { common: "Cape Verde", official: "Republic of Cabo Verde" },
    flags: { svg: "https://flagcdn.com/cv.svg" },
    capital: ["Praia"],
    region: "Africa",
    subregion: "Western Africa",
    population: 555988,
    languages: { por: "Portuguese" },
    currencies: { CVE: { name: "Cape Verdean escudo", symbol: "Esc" } },
    timezones: ["UTC-01:00"],
    cca2: "CV",
    cca3: "CPV",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["38"] },
    borders: []
  },
  {
    name: { common: "Central African Republic", official: "Central African Republic" },
    flags: { svg: "https://flagcdn.com/cf.svg" },
    capital: ["Bangui"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 4829764,
    languages: { fra: "French", sag: "Sango" },
    currencies: { XAF: { name: "Central African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "CF",
    cca3: "CAF",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["36"] },
    borders: ["CMR", "TCD", "COD", "COG", "SSD", "SDN"]
  },
  {
    name: { common: "Chad", official: "Republic of Chad" },
    flags: { svg: "https://flagcdn.com/td.svg" },
    capital: ["N'Djamena"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 16425859,
    languages: { ara: "Arabic", fra: "French" },
    currencies: { XAF: { name: "Central African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "TD",
    cca3: "TCD",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["35"] },
    borders: ["CMR", "CAF", "LBY", "NER", "NGA", "SSD"]
  },
  {
    name: { common: "Comoros", official: "Union of the Comoros" },
    flags: { svg: "https://flagcdn.com/km.svg" },
    capital: ["Moroni"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 869595,
    languages: { ara: "Arabic", fra: "French", zdj: "Comorian" },
    currencies: { KMF: { name: "Comorian franc", symbol: "Fr" } },
    timezones: ["UTC+03:00"],
    cca2: "KM",
    cca3: "COM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["69"] },
    borders: []
  },
  {
    name: { common: "Democratic Republic of the Congo", official: "Democratic Republic of the Congo" },
    flags: { svg: "https://flagcdn.com/cd.svg" },
    capital: ["Kinshasa"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 108407721,
    languages: { fra: "French", kon: "Kikongo", lin: "Lingala", lua: "Tshiluba", swa: "Swahili" },
    currencies: { CDF: { name: "Congolese franc", symbol: "Fr" } },
    timezones: ["UTC+01:00", "UTC+02:00"],
    cca2: "CD",
    cca3: "COD",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["42"] },
    borders: ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"]
  },
  {
    name: { common: "Republic of the Congo", official: "Republic of the Congo" },
    flags: { svg: "https://flagcdn.com/cg.svg" },
    capital: ["Brazzaville"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 5518092,
    languages: { fra: "French", kon: "Kikongo", lin: "Lingala" },
    currencies: { XAF: { name: "Central African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "CG",
    cca3: "COG",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["42"] },
    borders: ["AGO", "CMR", "CAF", "COD", "GAB"]
  },
  {
    name: { common: "Djibouti", official: "Republic of Djibouti" },
    flags: { svg: "https://flagcdn.com/dj.svg" },
    capital: ["Djibouti"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 988002,
    languages: { ara: "Arabic", fra: "French" },
    currencies: { DJF: { name: "Djiboutian franc", symbol: "Fr" } },
    timezones: ["UTC+03:00"],
    cca2: "DJ",
    cca3: "DJI",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["53"] },
    borders: ["ERI", "ETH", "SOM"]
  },
  {
    name: { common: "Equatorial Guinea", official: "Republic of Equatorial Guinea" },
    flags: { svg: "https://flagcdn.com/gq.svg" },
    capital: ["Malabo"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 1402985,
    languages: { fra: "French", por: "Portuguese", spa: "Spanish" },
    currencies: { XAF: { name: "Central African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "GQ",
    cca3: "GNQ",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["40"] },
    borders: ["CMR", "GAB"]
  },
  {
    name: { common: "Eritrea", official: "State of Eritrea" },
    flags: { svg: "https://flagcdn.com/er.svg" },
    capital: ["Asmara"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 5352000,
    languages: { ara: "Arabic", enm: "Modern Standard Arabic", tir: "Tigrinya" },
    currencies: { ERN: { name: "Eritrean nakfa", symbol: "Nfk" } },
    timezones: ["UTC+03:00"],
    cca2: "ER",
    cca3: "ERI",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["91"] },
    borders: ["DJI", "ETH", "SDN"]
  },
  {
    name: { common: "Eswatini", official: "Kingdom of Eswatini" },
    flags: { svg: "https://flagcdn.com/sz.svg" },
    capital: ["Mbabane"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 1160164,
    languages: { eng: "English", ssw: "Swazi" },
    currencies: { SZL: { name: "Swazi lilangeni", symbol: "L" }, ZAR: { name: "South African rand", symbol: "R" } },
    timezones: ["UTC+02:00"],
    cca2: "SZ",
    cca3: "SWZ",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["68"] },
    borders: ["MOZ", "ZAF"]
  },
  {
    name: { common: "Ethiopia", official: "Federal Democratic Republic of Ethiopia" },
    flags: { svg: "https://flagcdn.com/et.svg" },
    capital: ["Addis Ababa"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 114963583,
    languages: { amh: "Amharic" },
    currencies: { ETB: { name: "Ethiopian birr", symbol: "Br" } },
    timezones: ["UTC+03:00"],
    cca2: "ET",
    cca3: "ETH",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["51"] },
    borders: ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"]
  },
  {
    name: { common: "Gabon", official: "Gabonese Republic" },
    flags: { svg: "https://flagcdn.com/ga.svg" },
    capital: ["Libreville"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 2225734,
    languages: { fra: "French" },
    currencies: { XAF: { name: "Central African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "GA",
    cca3: "GAB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["41"] },
    borders: ["CMR", "COG", "GNQ"]
  },
  {
    name: { common: "Gambia", official: "Republic of the Gambia" },
    flags: { svg: "https://flagcdn.com/gm.svg" },
    capital: ["Banjul"],
    region: "Africa",
    subregion: "Western Africa",
    population: 2416664,
    languages: { eng: "English" },
    currencies: { GMD: { name: "dalasi", symbol: "D" } },
    timezones: ["UTC+00:00"],
    cca2: "GM",
    cca3: "GMB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["20"] },
    borders: ["SEN"]
  },
  {
    name: { common: "Ghana", official: "Republic of Ghana" },
    flags: { svg: "https://flagcdn.com/gh.svg" },
    capital: ["Accra"],
    region: "Africa",
    subregion: "Western Africa",
    population: 31072945,
    languages: { eng: "English" },
    currencies: { GHS: { name: "Ghanaian cedi", symbol: "₵" } },
    timezones: ["UTC+00:00"],
    cca2: "GH",
    cca3: "GHA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["33"] },
    borders: ["BFA", "CIV", "TGO"]
  },
  {
    name: { common: "Guinea", official: "Republic of Guinea" },
    flags: { svg: "https://flagcdn.com/gn.svg" },
    capital: ["Conakry"],
    region: "Africa",
    subregion: "Western Africa",
    population: 13132792,
    languages: { fra: "French" },
    currencies: { GNF: { name: "Guinean franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "GN",
    cca3: "GIN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["24"] },
    borders: ["CIV", "LBR", "MLI", "SEN", "SLE"]
  },
  {
    name: { common: "Guinea-Bissau", official: "Republic of Guinea-Bissau" },
    flags: { svg: "https://flagcdn.com/gw.svg" },
    capital: ["Bissau"],
    region: "Africa",
    subregion: "Western Africa",
    population: 1967998,
    languages: { por: "Portuguese", pov: "Upper Guinea Creole" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "GW",
    cca3: "GNB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["45"] },
    borders: ["GIN", "SEN"]
  },
  {
    name: { common: "Ivory Coast", official: "Republic of Côte d'Ivoire" },
    flags: { svg: "https://flagcdn.com/ci.svg" },
    capital: ["Yamoussoukro"],
    region: "Africa",
    subregion: "Western Africa",
    population: 26378275,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "CI",
    cca3: "CIV",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["25"] },
    borders: ["BFA", "GHA", "GIN", "LBR", "MLI"]
  },
  {
    name: { common: "Kenya", official: "Republic of Kenya" },
    flags: { svg: "https://flagcdn.com/ke.svg" },
    capital: ["Nairobi"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 53771300,
    languages: { eng: "English", swa: "Swahili" },
    currencies: { KES: { name: "Kenyan shilling", symbol: "Sh" } },
    timezones: ["UTC+03:00"],
    cca2: "KE",
    cca3: "KEN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["54"] },
    borders: ["ETH", "SOM", "SSD", "TZA", "UGA"]
  },
  {
    name: { common: "Lesotho", official: "Kingdom of Lesotho" },
    flags: { svg: "https://flagcdn.com/ls.svg" },
    capital: ["Maseru"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 2142252,
    languages: { eng: "English", sot: "Sotho" },
    currencies: { LSL: { name: "Lesotho loti", symbol: "L" }, ZAR: { name: "South African rand", symbol: "R" } },
    timezones: ["UTC+02:00"],
    cca2: "LS",
    cca3: "LSO",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["66"] },
    borders: ["ZAF"]
  },
  {
    name: { common: "Liberia", official: "Republic of Liberia" },
    flags: { svg: "https://flagcdn.com/lr.svg" },
    capital: ["Monrovia"],
    region: "Africa",
    subregion: "Western Africa",
    population: 5057677,
    languages: { eng: "English" },
    currencies: { LRD: { name: "Liberian dollar", symbol: "$" } },
    timezones: ["UTC+00:00"],
    cca2: "LR",
    cca3: "LBR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["31"] },
    borders: ["GIN", "CIV", "SLE"]
  },
  {
    name: { common: "Libya", official: "State of Libya" },
    flags: { svg: "https://flagcdn.com/ly.svg" },
    capital: ["Tripoli"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 6871287,
    languages: { ara: "Arabic" },
    currencies: { LYD: { name: "Libyan dinar", symbol: "ل.د" } },
    timezones: ["UTC+01:00"],
    cca2: "LY",
    cca3: "LBY",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["18"] },
    borders: ["DZA", "TCD", "EGY", "NER", "SDN", "TUN"]
  },
  {
    name: { common: "Madagascar", official: "Republic of Madagascar" },
    flags: { svg: "https://flagcdn.com/mg.svg" },
    capital: ["Antananarivo"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 27691019,
    languages: { fra: "French", mlg: "Malagasy" },
    currencies: { MGA: { name: "Malagasy ariary", symbol: "Ar" } },
    timezones: ["UTC+03:00"],
    cca2: "MG",
    cca3: "MDG",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["61"] },
    borders: []
  },
  {
    name: { common: "Malawi", official: "Republic of Malawi" },
    flags: { svg: "https://flagcdn.com/mw.svg" },
    capital: ["Lilongwe"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 19129955,
    languages: { eng: "English", nya: "Chewa" },
    currencies: { MWK: { name: "Malawian kwacha", symbol: "MK" } },
    timezones: ["UTC+02:00"],
    cca2: "MW",
    cca3: "MWI",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["65"] },
    borders: ["MOZ", "TZA", "ZMB"]
  },
  {
    name: { common: "Mali", official: "Republic of Mali" },
    flags: { svg: "https://flagcdn.com/ml.svg" },
    capital: ["Bamako"],
    region: "Africa",
    subregion: "Western Africa",
    population: 20250834,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "ML",
    cca3: "MLI",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["23"] },
    borders: ["DZA", "BFA", "GIN", "CIV", "MRT", "NER", "SEN"]
  },
  {
    name: { common: "Mauritania", official: "Islamic Republic of Mauritania" },
    flags: { svg: "https://flagcdn.com/mr.svg" },
    capital: ["Nouakchott"],
    region: "Africa",
    subregion: "Western Africa",
    population: 4649660,
    languages: { ara: "Arabic" },
    currencies: { MRU: { name: "Mauritanian ouguiya", symbol: "UM" } },
    timezones: ["UTC+00:00"],
    cca2: "MR",
    cca3: "MRT",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["22"] },
    borders: ["DZA", "MLI", "SEN", "ESH"]
  },
  {
    name: { common: "Mauritius", official: "Republic of Mauritius" },
    flags: { svg: "https://flagcdn.com/mu.svg" },
    capital: ["Port Louis"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 1265303,
    languages: { eng: "English", fra: "French", mfe: "Mauritian Creole" },
    currencies: { MUR: { name: "Mauritian rupee", symbol: "₨" } },
    timezones: ["UTC+04:00"],
    cca2: "MU",
    cca3: "MUS",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["30"] },
    borders: []
  },
  {
    name: { common: "Morocco", official: "Kingdom of Morocco" },
    flags: { svg: "https://flagcdn.com/ma.svg" },
    capital: ["Rabat"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 36910558,
    languages: { ara: "Arabic", ber: "Berber" },
    currencies: { MAD: { name: "Moroccan dirham", symbol: "د.م." } },
    timezones: ["UTC+00:00"],
    cca2: "MA",
    cca3: "MAR",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["12"] },
    borders: ["DZA", "ESH", "ESP"]
  },
  {
    name: { common: "Mozambique", official: "Republic of Mozambique" },
    flags: { svg: "https://flagcdn.com/mz.svg" },
    capital: ["Maputo"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 31255435,
    languages: { por: "Portuguese" },
    currencies: { MZN: { name: "Mozambican metical", symbol: "MT" } },
    timezones: ["UTC+02:00"],
    cca2: "MZ",
    cca3: "MOZ",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["58"] },
    borders: ["MWI", "ZAF", "SWZ", "TZA", "ZMB", "ZW"]
  },
  {
    name: { common: "Namibia", official: "Republic of Namibia" },
    flags: { svg: "https://flagcdn.com/na.svg" },
    capital: ["Windhoek"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 2540916,
    languages: { eng: "English", afr: "Afrikaans" },
    currencies: { NAD: { name: "Namibian dollar", symbol: "$" }, ZAR: { name: "South African rand", symbol: "R" } },
    timezones: ["UTC+01:00", "UTC+02:00"],
    cca2: "NA",
    cca3: "NAM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["64"] },
    borders: ["AGO", "BWA", "ZAF", "ZMB"]
  },
  {
    name: { common: "Niger", official: "Republic of Niger" },
    flags: { svg: "https://flagcdn.com/ne.svg" },
    capital: ["Niamey"],
    region: "Africa",
    subregion: "Western Africa",
    population: 24206636,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+01:00"],
    cca2: "NE",
    cca3: "NER",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["27"] },
    borders: ["DZA", "BEN", "BFA", "TCD", "LBY", "MLI", "NGA"]
  },
  {
    name: { common: "Nigeria", official: "Federal Republic of Nigeria" },
    flags: { svg: "https://flagcdn.com/ng.svg" },
    capital: ["Abuja"],
    region: "Africa",
    subregion: "Western Africa",
    population: 206139587,
    languages: { eng: "English" },
    currencies: { NGN: { name: "Nigerian naira", symbol: "₦" } },
    timezones: ["UTC+01:00"],
    cca2: "NG",
    cca3: "NGA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["34"] },
    borders: ["BEN", "CMR", "TCD", "NER"]
  },
  {
    name: { common: "Rwanda", official: "Republic of Rwanda" },
    flags: { svg: "https://flagcdn.com/rw.svg" },
    capital: ["Kigali"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 12952209,
    languages: { eng: "English", fra: "French", kin: "Kinyarwanda" },
    currencies: { RWF: { name: "Rwandan franc", symbol: "Fr" } },
    timezones: ["UTC+02:00"],
    cca2: "RW",
    cca3: "RWA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["50"] },
    borders: ["BDI", "COD", "TZA", "UGA"]
  },
  {
    name: { common: "São Tomé and Príncipe", official: "Democratic Republic of São Tomé and Príncipe" },
    flags: { svg: "https://flagcdn.com/st.svg" },
    capital: ["São Tomé"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 219161,
    languages: { por: "Portuguese" },
    currencies: { STN: { name: "São Tomé and Príncipe dobra", symbol: "Db" } },
    timezones: ["UTC+00:00"],
    cca2: "ST",
    cca3: "STP",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["39"] },
    borders: []
  },
  {
    name: { common: "Senegal", official: "Republic of Senegal" },
    flags: { svg: "https://flagcdn.com/sn.svg" },
    capital: ["Dakar"],
    region: "Africa",
    subregion: "Western Africa",
    population: 16743930,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "SN",
    cca3: "SEN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["21"] },
    borders: ["GMB", "GIN", "GNB", "MLI", "MRT"]
  },
  {
    name: { common: "Seychelles", official: "Republic of Seychelles" },
    flags: { svg: "https://flagcdn.com/sc.svg" },
    capital: ["Victoria"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 98462,
    languages: { eng: "English", fra: "French", crs: "Seychellois Creole" },
    currencies: { SCR: { name: "Seychellois rupee", symbol: "₨" } },
    timezones: ["UTC+04:00"],
    cca2: "SC",
    cca3: "SYC",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["48"] },
    borders: []
  },
  {
    name: { common: "Sierra Leone", official: "Republic of Sierra Leone" },
    flags: { svg: "https://flagcdn.com/sl.svg" },
    capital: ["Freetown"],
    region: "Africa",
    subregion: "Western Africa",
    population: 7976985,
    languages: { eng: "English" },
    currencies: { SLL: { name: "Sierra Leonean leone", symbol: "Le" } },
    timezones: ["UTC+00:00"],
    cca2: "SL",
    cca3: "SLE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["32"] },
    borders: ["GIN", "LBR"]
  },
  {
    name: { common: "Somalia", official: "Federal Republic of Somalia" },
    flags: { svg: "https://flagcdn.com/so.svg" },
    capital: ["Mogadishu"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 15893219,
    languages: { ara: "Arabic", som: "Somali" },
    currencies: { SOS: { name: "Somali shilling", symbol: "Sh" } },
    timezones: ["UTC+03:00"],
    cca2: "SO",
    cca3: "SOM",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["52"] },
    borders: ["DJI", "ETH", "KEN"]
  },
  {
    name: { common: "South Africa", official: "Republic of South Africa" },
    flags: { svg: "https://flagcdn.com/za.svg" },
    capital: ["Pretoria"],
    region: "Africa",
    subregion: "Southern Africa",
    population: 59308690,
    languages: { afr: "Afrikaans", eng: "English", nbl: "Southern Ndebele", nso: "Northern Sotho", sot: "Southern Sotho", ss: "Swati", tsn: "Tswana", tso: "Tsonga", ven: "Venda", xho: "Xhosa", zul: "Zulu" },
    currencies: { ZAR: { name: "South African rand", symbol: "R" } },
    timezones: ["UTC+02:00"],
    cca2: "ZA",
    cca3: "ZAF",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["7"] },
    borders: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"]
  },
  {
    name: { common: "South Sudan", official: "Republic of South Sudan" },
    flags: { svg: "https://flagcdn.com/ss.svg" },
    capital: ["Juba"],
    region: "Africa",
    subregion: "Middle Africa",
    population: 11193729,
    languages: { eng: "English" },
    currencies: { SSP: { name: "South Sudanese pound", symbol: "£" } },
    timezones: ["UTC+03:00"],
    cca2: "SS",
    cca3: "SSD",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["11"] },
    borders: ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"]
  },
  {
    name: { common: "Sudan", official: "Republic of the Sudan" },
    flags: { svg: "https://flagcdn.com/sd.svg" },
    capital: ["Khartoum"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 43849269,
    languages: { ara: "Arabic", eng: "English" },
    currencies: { SDG: { name: "Sudanese pound", symbol: "ج.س." } },
    timezones: ["UTC+03:00"],
    cca2: "SD",
    cca3: "SDN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["49"] },
    borders: ["CAF", "TCD", "EGY", "ERI", "ETH", "LBY", "SSD"]
  },
  {
    name: { common: "Tanzania", official: "United Republic of Tanzania" },
    flags: { svg: "https://flagcdn.com/tz.svg" },
    capital: ["Dodoma"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 59734213,
    languages: { eng: "English", swa: "Swahili" },
    currencies: { TZS: { name: "Tanzanian shilling", symbol: "Sh" } },
    timezones: ["UTC+03:00"],
    cca2: "TZ",
    cca3: "TZA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["55"] },
    borders: ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"]
  },
  {
    name: { common: "Togo", official: "Togolese Republic" },
    flags: { svg: "https://flagcdn.com/tg.svg" },
    capital: ["Lomé"],
    region: "Africa",
    subregion: "Western Africa",
    population: 8278737,
    languages: { fra: "French" },
    currencies: { XOF: { name: "West African CFA franc", symbol: "Fr" } },
    timezones: ["UTC+00:00"],
    cca2: "TG",
    cca3: "TGO",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["28"] },
    borders: ["BEN", "BFA", "GHA"]
  },
  {
    name: { common: "Tunisia", official: "Tunisian Republic" },
    flags: { svg: "https://flagcdn.com/tn.svg" },
    capital: ["Tunis"],
    region: "Africa",
    subregion: "Northern Africa",
    population: 11818619,
    languages: { ara: "Arabic" },
    currencies: { TND: { name: "Tunisian dinar", symbol: "د.ت" } },
    timezones: ["UTC+01:00"],
    cca2: "TN",
    cca3: "TUN",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["16"] },
    borders: ["DZA", "LBY"]
  },
  {
    name: { common: "Uganda", official: "Republic of Uganda" },
    flags: { svg: "https://flagcdn.com/ug.svg" },
    capital: ["Kampala"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 45741000,
    languages: { eng: "English", swa: "Swahili" },
    currencies: { UGX: { name: "Ugandan shilling", symbol: "Sh" } },
    timezones: ["UTC+03:00"],
    cca2: "UG",
    cca3: "UGA",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["56"] },
    borders: ["COD", "KEN", "RWA", "SSD", "TZA"]
  },
  {
    name: { common: "Zambia", official: "Republic of Zambia" },
    flags: { svg: "https://flagcdn.com/zm.svg" },
    capital: ["Lusaka"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 18383956,
    languages: { eng: "English" },
    currencies: { ZMW: { name: "Zambian kwacha", symbol: "ZK" } },
    timezones: ["UTC+02:00"],
    cca2: "ZM",
    cca3: "ZMB",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["60"] },
    borders: ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"]
  },
  {
    name: { common: "Zimbabwe", official: "Republic of Zimbabwe" },
    flags: { svg: "https://flagcdn.com/zw.svg" },
    capital: ["Harare"],
    region: "Africa",
    subregion: "Eastern Africa",
    population: 14862927,
    languages: { eng: "English", nde: "Northern Ndebele", nso: "Northern Sotho", sna: "Shona", sot: "Southern Sotho", tsn: "Tswana", tso: "Tsonga", ven: "Venda", xho: "Xhosa", zul: "Zulu" },
    currencies: { BWP: { name: "Botswana pula", symbol: "P" }, KZ: { name: "Zimbabwean bonds", symbol: "$" }, ZWL: { name: "Zimbabwean dollar", symbol: "$" } },
    timezones: ["UTC+02:00"],
    cca2: "ZW",
    cca3: "ZWE",
    independent: true,
    status: " sovereign",
    unMember: true,
    idd: { root: "+2", suffixes: ["63"] },
    borders: ["BWA", "MOZ", "ZAF", "ZMB"]
  }
];

/**
 * Fungsi untuk mengambil semua negara (menggunakan mock data sementara)
 * @async
 * @function getAllCountries
 * @returns {Promise<Array>} Promise yang berisi array objek negara
 * @throws {Error} Jika terjadi kesalahan saat mengambil data
 */
export const getAllCountries = async () => {
  try {
    // Simulasikan delay jaringan
    await new Promise(resolve => setTimeout(resolve, 500));
    return mockCountries;
  } catch (error) {
    console.error('Gagal mengambil data negara:', error);
    throw error;
  }
};

/**
 * Fungsi untuk mencari negara berdasarkan nama (menggunakan mock data sementara)
 * @async
 * @function getCountryByName
 * @param {string} name - Nama negara yang dicari
 * @returns {Promise<Array>} Promise yang berisi array objek negara
 * @throws {Error} Jika terjadi kesalahan saat mengambil data
 */
export const getCountryByName = async (name) => {
  try {
    // Simulasikan delay jaringan
    await new Promise(resolve => setTimeout(resolve, 500));
    const lowerCaseName = name.toLowerCase();
    const foundCountries = mockCountries.filter(country =>
      country.name.common.toLowerCase().includes(lowerCaseName) ||
      country.name.official.toLowerCase().includes(lowerCaseName)
    );

    if (foundCountries.length === 0) {
      throw new Error('Negara tidak ditemukan');
    }

    return foundCountries;
  } catch (error) {
    console.error('Gagal mengambil data negara berdasarkan nama:', error);
    throw error;
  }
};

/**
 * Fungsi untuk mengambil negara berdasarkan kode (menggunakan mock data sementara)
 * @async
 * @function getCountryByCode
 * @param {string} code - Kode negara (2 huruf atau 3 huruf)
 * @returns {Promise<Object>} Promise yang berisi objek negara
 * @throws {Error} Jika terjadi kesalahan saat mengambil data
 */
export const getCountryByCode = async (code) => {
  try {
    // Simulasikan delay jaringan
    await new Promise(resolve => setTimeout(resolve, 500));
    const foundCountry = mockCountries.find(country =>
      country.cca2.toLowerCase() === code.toLowerCase() ||
      country.cca3.toLowerCase() === code.toLowerCase()
    );

    if (!foundCountry) {
      throw new Error('Negara tidak ditemukan');
    }

    return foundCountry;
  } catch (error) {
    console.error('Gagal mengambil data negara berdasarkan kode:', error);
    throw error;
  }
};

/**
 * Fungsi untuk mengambil negara berdasarkan region (menggunakan mock data sementara)
 * @async
 * @function getCountriesByRegion
 * @param {string} region - Region negara yang dicari
 * @returns {Promise<Array>} Promise yang berisi array objek negara
 * @throws {Error} Jika terjadi kesalahan saat mengambil data
 */
export const getCountriesByRegion = async (region) => {
  try {
    // Simulasikan delay jaringan
    await new Promise(resolve => setTimeout(resolve, 500));
    const filteredCountries = mockCountries.filter(country =>
      country.region.toLowerCase() === region.toLowerCase()
    );

    if (filteredCountries.length === 0) {
      throw new Error('Tidak ada negara ditemukan untuk region ini');
    }

    return filteredCountries;
  } catch (error) {
    console.error('Gagal mengambil data negara berdasarkan region:', error);
    throw error;
  }
};